services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 15

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy

  pgadmin:
    image: elestio/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  # phppgadmin:
  #   image: dockage/phppgadmin
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - PHP_PG_ADMIN_SERVER=host.docker.internal
  #     - PHP_PG_ADMIN_SERVER_PORT=5432
  #     - PHP_PG_ADMIN_SERVER_SSL=false
  #     - PHP_PG_ADMIN_SERVER_VERBOSE=false
  #     - PHP_PG_ADMIN_DEFAULT_LANG=ru
  #     - PHP_PG_ADMIN_AUTO_COMPLETE=true
  #   depends_on:
  #     - db